# Generated by Django 3.0.8 on 2020-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_comment_accepted'),
        ('users', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_blogs',
            field=models.ManyToManyField(to='blogs.Blog'),
        ),
    ]
