# Generated by Django 3.0.8 on 2020-08-26 08:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20200826_1233'),
        ('users', '0011_auto_20200823_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[100, 100], upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_blogs',
            field=models.ManyToManyField(blank=True, to='blogs.Blog'),
        ),
    ]
