# Generated by Django 3.0.8 on 2020-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200809_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blog',
            name='_thumbnail',
            field=models.TextField(db_column='thumbnail', null=True, verbose_name='thumbnail'),
        ),
    ]
