# Generated by Django 3.0.8 on 2020-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200812_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='_thumbnail',
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.TextField(db_column='thumbnail', null=True),
        ),
    ]
