# Generated by Django 3.0.8 on 2020-08-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200812_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumbnail',
            new_name='_thumbnail',
        ),
    ]
