# Generated by Django 3.0.8 on 2020-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200819_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='_thumbnail',
            field=models.ImageField(blank=True, db_column='thumbnail', null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
