# Generated by Django 3.0.8 on 2020-08-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200820_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='_thumbnail',
            new_name='thumbnail',
        ),
    ]
