# Generated by Django 3.0.8 on 2020-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20200820_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, db_column='thumbnail', null=True, upload_to='images'),
        ),
    ]
