# Generated by Django 3.0.8 on 2020-08-20 16:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200820_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, db_column='thumbnail', force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to='images'),
        ),
    ]
