# Generated by Django 3.0.8 on 2020-08-26 08:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200820_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[300, 300], upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
