# Generated by Django 3.0.8 on 2020-08-21 16:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_look',
        ),
        migrations.AddField(
            model_name='video',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.IntegerField(blank=True),
        ),
    ]
