# Generated by Django 3.0.8 on 2020-08-22 06:24

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
        ),
    ]
