# Generated by Django 3.0.8 on 2020-08-22 06:30

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_at',
        ),
        migrations.AddField(
            model_name='course',
            name='published_datetime',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='published_datetime',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
