# Generated by Django 3.0.8 on 2020-08-26 08:03

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200822_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
