# Generated by Django 3.0.8 on 2020-08-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='owner',
        ),
    ]
