# Generated by Django 3.0.8 on 2020-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0008_auto_20200826_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
